# Generated by Django 4.1.5 on 2023-01-23 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='conclusionartifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.conclusionartifact'),
        ),
        migrations.AlterField(
            model_name='method',
            name='dataartifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.dataartifact'),
        ),
        migrations.AlterField(
            model_name='method',
            name='experimentartifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.experimentartifact'),
        ),
        migrations.AlterField(
            model_name='method',
            name='hypothesisartifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.hypothesisartifact'),
        ),
    ]
