# Generated by Django 4.1.4 on 2022-12-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='user',
        ),
    ]
